SELECT DISTINCT ?item ?itemLabel ?area ?unicode WHERE {
  ?item (wdt:P31/(wdt:P279*)) wd:Q5107.
  ?item wdt:P361 wd:Q2.
  ?item wdt:P2046 ?area.
  OPTIONAL { ?item wdt:P487 ?unicode. }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
}